title: <p align="Center" >Prithipa A</p>
logo: /assets/img/GettyImages-988013222-scaled-e1618857975729.jpg
description: An Infrastructure Engineer
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
